In [1]:
import pandas as pd

In [2]:
vine_review_df = pd.read_csv('vine_table.csv')
vine_review_df.head(12)

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,R35T75OLUGHL5C,4.0,0.0,0.0,N,Y
1,R2BV735O46BN33,5.0,0.0,0.0,N,Y
2,R2NBEUGPQQGXP1,4.0,0.0,0.0,N,Y
3,R17LLAOJ8ITK0S,3.0,1.0,1.0,N,Y
4,R39PEQBT5ISEF4,1.0,0.0,0.0,N,Y
5,R3GNM3SU9VHJFT,4.0,1.0,1.0,N,Y
6,R2Y81OP0EK467,5.0,0.0,0.0,N,Y
7,R2LFGSI6HAYH5F,5.0,1.0,1.0,N,Y
8,R297G6ED1IQO7W,5.0,1.0,1.0,N,Y
9,RE27RFC6101N6,5.0,0.0,0.0,N,Y
10,R3BPDME6E94W8Z,5.0,0.0,0.0,N,Y
11,R2P08O1RILUOX3,3.0,0.0,0.0,N,Y

In [3]:
# 1. Filter the data and create a new DataFrame or table to retrieve
# all the rows where the total_votes count is equal to or greater than 20

In [4]:
votes_vine_df = vine_review_df[vine_review_df['total_votes'] >= 20]
votes_vine_df.head(12)

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
65,R2FP3U4NHNFNL2,5.0,25.0,29.0,N,Y
159,R1UUK1977O38MU,5.0,31.0,31.0,N,Y
603,RXO216LWUDV6O,3.0,29.0,31.0,N,Y
655,R3NMJF7EBMM19V,3.0,26.0,27.0,N,Y
935,R2ZY0ZBDUO0XUY,3.0,20.0,21.0,N,Y
939,RBDVHX7PMQEKM,5.0,35.0,39.0,N,Y
945,RGO3KSDXYWTGU,4.0,26.0,26.0,N,Y
1027,R2O4P39D0ALCQK,2.0,14.0,43.0,N,Y
1030,R1E1PQGHWGO3Q1,1.0,89.0,96.0,N,Y
1064,R1XOXXUVYZEDJB,5.0,22.0,22.0,N,Y
1096,R7SHITUU5UG9U,5.0,27.0,27.0,N,Y
1389,R230TLHU91M5Y3,4.0,21.0,21.0,N,Y

In [5]:
# 2. Filter the new DataFrame or table created in Step 1 and create a new DataFrame or table to retrieve
# all the rows where the number of helpful_votes divided by total_votes is equal to or greater than 50%.

In [6]:
helpful_vine_df = votes_vine_df.loc[votes_vine_df.helpful_votes / votes_vine_df.total_votes >= 0.5]
helpful_vine_df.head(12)

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
65,R2FP3U4NHNFNL2,5.0,25.0,29.0,N,Y
159,R1UUK1977O38MU,5.0,31.0,31.0,N,Y
603,RXO216LWUDV6O,3.0,29.0,31.0,N,Y
655,R3NMJF7EBMM19V,3.0,26.0,27.0,N,Y
935,R2ZY0ZBDUO0XUY,3.0,20.0,21.0,N,Y
939,RBDVHX7PMQEKM,5.0,35.0,39.0,N,Y
945,RGO3KSDXYWTGU,4.0,26.0,26.0,N,Y
1030,R1E1PQGHWGO3Q1,1.0,89.0,96.0,N,Y
1064,R1XOXXUVYZEDJB,5.0,22.0,22.0,N,Y
1096,R7SHITUU5UG9U,5.0,27.0,27.0,N,Y
1389,R230TLHU91M5Y3,4.0,21.0,21.0,N,Y
1424,RHR5MKO23K9TU,5.0,26.0,30.0,N,Y

In [7]:
# 3. Filter the DataFrame or table created in Step 2, and create a new DataFrame or table that retrieves 
# all the rows where a review was written as part of the Vine program (paid

In [8]:
reviews_written = helpful_vine_df[helpful_vine_df['vine'] == 'Y']
reviews_written.head(12)

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
30395,R3KPC0NBUDASX3,5.0,25.0,25.0,Y,N
206171,R119P2A95GGXX4,5.0,26.0,28.0,Y,N
222172,R1HKIRME8AJ89Z,5.0,79.0,82.0,Y,N
281437,R3FY3GMBGOBR22,5.0,12.0,20.0,Y,N
287862,R15KH3FBSVYGBU,5.0,32.0,37.0,Y,N
295268,R22XZEQLVLWW49,5.0,28.0,33.0,Y,N
303981,R2OIQYVAL9D63R,4.0,59.0,65.0,Y,N
315931,R1W3KCDHM6BMZT,4.0,37.0,38.0,Y,N
392314,R3KDMPS96IJ10R,2.0,15.0,21.0,Y,N
396815,R1XWEI58A7VKLB,5.0,123.0,128.0,Y,N
406354,R1CJWM6CMWKSA1,4.0,31.0,33.0,Y,N
415531,R39I3FUDBKZM3Y,5.0,34.0,38.0,Y,N

In [9]:
# Repeat Step 3, but this time retrieve all the rows where the review was not part of the Vine program (unpaid)

In [10]:
not_paid_reviews = helpful_vine_df[helpful_vine_df['vine'] == 'N']
not_paid_reviews.head(12)

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
65,R2FP3U4NHNFNL2,5.0,25.0,29.0,N,Y
159,R1UUK1977O38MU,5.0,31.0,31.0,N,Y
603,RXO216LWUDV6O,3.0,29.0,31.0,N,Y
655,R3NMJF7EBMM19V,3.0,26.0,27.0,N,Y
935,R2ZY0ZBDUO0XUY,3.0,20.0,21.0,N,Y
939,RBDVHX7PMQEKM,5.0,35.0,39.0,N,Y
945,RGO3KSDXYWTGU,4.0,26.0,26.0,N,Y
1030,R1E1PQGHWGO3Q1,1.0,89.0,96.0,N,Y
1064,R1XOXXUVYZEDJB,5.0,22.0,22.0,N,Y
1096,R7SHITUU5UG9U,5.0,27.0,27.0,N,Y
1389,R230TLHU91M5Y3,4.0,21.0,21.0,N,Y
1424,RHR5MKO23K9TU,5.0,26.0,30.0,N,Y

In [11]:
# Determine the total number of reviews, the number of 5-star reviews, 
# and the percentage of 5-star reviews for the two types of review (paid vs unpaid).

In [12]:
paid_reviews_written_total = len(reviews_written)
paid_reviews_written_total

107

In [13]:
not_paid_reviews_total = len(not_paid_reviews)
not_paid_reviews_total

39869

In [14]:
five_star_total_paid = len(reviews_written[reviews_written['star_rating']==5])
five_star_total_paid

56

In [15]:
five_star_total_not_paid = len(not_paid_reviews[not_paid_reviews['star_rating']==5])
five_star_total_not_paid

21005

In [16]:
# Percentage of 5-star reviews (paid)

In [17]:
five_star_total_paid/paid_reviews_written_total

0.5233644859813084

In [18]:
# Percentage of 5-star reviews (not paid)

In [19]:
five_star_total_not_paid/not_paid_reviews_total

0.5268504351751988